### ISSUE TITLE
Can't get it to work on windows.

### ISSUE THREAD

**Issue by AziRizvi** [po5/mpv-auto-chapters#1]
MPV Version: v0.38.0-743-gad7976c3
Script Version: Git Master
Curl Version: (Curl 8.11.0)
Guessit Version: v3.8.0
Windows Version: (Windows 10 22H2)

I can't get this to work on windows at all, I always get this error in the console.

![MPV_t90sIq1ej6](https://github.com/user-attachments/assets/205dab0a-f71a-4efa-90fe-4a7db0a528c6)

Guessit and Curl are both installed properly and are added to my environment variables and are accessible via terminal. (Curl comes pre-installed in Windows 10 in `C:\Windows\System32\` and I tried the script out with that version of curl and it kept throwing the same error at me so I thought this might be perhaps because it's an older version of curl so I downloaded the latest curl release from the website, unlocked the system32 curl file which was locked by TrustedInstaller and after that I placed the latest curl release in that directory and that still did not work, I'm getting the same error.

![WindowsTerminal_J0Ro2tACRf](https://github.com/user-attachments/assets/d8c40597-7794-4695-a474-34af5dab222c)

Help in getting this to work will be appreciated.

**Comment by AziRizvi** [comment]
I'm not sure what's changed exactly but somehow the script has now started to work and is not throwing that error out anymore, my settings and everything is exactly the same as before.

You can close this ticket if you want to, or maybe something in the script needs fixing, idk. 
If I run into any issues again I will share them in a new ticket I guess.

**Comment by po5** [comment]
I know an issue you can run into on Windows is that on some systems you'll get SSL certificate errors. Doesn't happen on my install and I couldn't find a solution when troubleshooting with a friend who had the issue.

**Comment by AziRizvi** [comment]
Well it's working fine for now at least but I don't know when/if the issue will start up again.

On a side note, a suggestion, would it not be better just to include the curl and guessit binaries with script and just make the script use them kind of like how uosc does with ziggy? For the average user who just wants to quickly get the script up and running, downloading the binaries, setting them someplace in your pc where they won't be touched and then setting up the path environment variables adds an extra layer of difficulty.
